title: Portfolio
description: This is a basic website used to document my projects and work!
theme: just-the-docs

url: https://just-the-docs.github.io

# aux_links:
#   Linked IN: https://github.com/just-the-docs/just-the-docs-template


# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: dark

callouts_level: quiet # or loud
callouts:
  alternate:
    color: red
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    # title: Note
    color: green
  warning:
    title: Warning
    color: red

#Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
#Note: the main Just the Docs site does *not* use Google Analytics.
ga_tracking: G-QNR3P0VYKD
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
